version: '3'

services:
  app:
    build:
      context: ./php
      #dockerfile: ./php/Dockerfile
    image: sandbox_app
    container_name: app
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./var/www:/var/www

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "6969:80"
    volumes:
      - ./var/www:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
  
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    depends_on:
      - app
    
    